import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./provider";
import { AuthProvider } from "./AuthProvider";
import { UserProviders } from "./UserRecoilProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Suppiz | Beta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/fav/fav.png" />
        <title>Suppiz | Beta</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <Providers>
        <UserProviders>
          <AuthProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              {children}
            </body>
          </AuthProvider>
        </UserProviders>
      </Providers>
    </html>
  );
}
